---
title: "Untitled"
date: "`r format(Sys.time(), '%d %B, %Y')`"
format: pdf
---



## Preamble

Load libraries and set chunk options here.

```{r}
#| label: setup
#| warning: false
#| message: false
# set global chunk options: images will be 7x5 inches
# wrap output at 60 characters 
library(knitr) # for creating reproducible reports
library(formatR) # for formatting code in output file
library(here) # to facilitate reading in data using a relative path
library(lubridate) # for working with dates
library(ggplot2) # for plotting
opts_chunk$set(fig.width=7, fig.height=5, tidy.opts = list(width.cutoff = 60),
               tidy = TRUE)  
```

## Data

Read in data.

```{r}
coviddat <- read.csv(here("FW8051Data", "minnesota-history.csv"))
```



## Analysis

```{r}
#| fig-alt: Scatterplot of covid deaths by Julian date.
#| fig-align: center
#| out-width: 50%
#| fig-width: 6
#| fig-height: 4
#' Need to make sure R recognizes date as a true date variable
coviddat$date<-ymd(as.character(coviddat$date))
ggplot(coviddat, aes(date, death)) +
  geom_point() +
  xlab("") + 
  ylab("Number of Covid-Related Deaths in MN")
```


## Footer

We can create a reproducible report by clicking "Render" in Rstudio.
  
  

```{r}
sessionInfo()
```

